# Generated by Django 2.2.5 on 2019-11-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food',
            new_name='myfood',
        ),
    ]
